const dotenv = require("dotenv");
const mongoose = require("mongoose");
const {
  Reading,
  ReadingItem,
  Sura,
  Part,
  Page,
  Hotspot,
  LikedHotspot,
  SuraInReading,
  PartInReading,
} = require("./models/quraanModels");

const externalIndex = [
  {
    id: 1,
    suraId: 1,
    title: "الفاتحة",
    type: "مكية",
    pageNumber: 1,
    souraNumber: 1,
  },
  {
    id: 2,
    suraId: 2,
    title: "البقرة",
    type: "مدنية",
    pageNumber: 2,
    souraNumber: 2,
  },
  {
    id: 3,
    suraId: 3,
    title: "آل عمران",
    type: "مدنية",
    pageNumber: 50,
    souraNumber: 3,
  },
  {
    id: 4,
    suraId: 4,
    title: "النساء",
    type: "مدنية",
    pageNumber: 77,
    souraNumber: 4,
  },
  {
    id: 5,
    suraId: 5,
    title: "المائدة",
    type: "مدنية",
    pageNumber: 106,
    souraNumber: 5,
  },
  {
    id: 6,
    suraId: 6,
    title: "الأنعام",
    type: "مكية",
    pageNumber: 128,
    souraNumber: 6,
  },
  {
    id: 7,
    suraId: 7,
    title: "الأعراف",
    type: "مكية",
    pageNumber: 151,
    souraNumber: 7,
  },
  {
    id: 8,
    suraId: 8,
    title: "الأنفال",
    type: "مدنية",
    pageNumber: 177,
    souraNumber: 8,
  },
  {
    id: 9,
    suraId: 9,
    title: "التوبة",
    type: "مدنية",
    pageNumber: 187,
    souraNumber: 9,
  },
  {
    id: 10,
    suraId: 10,
    title: "يونس",
    type: "مكية",
    pageNumber: 208,
    souraNumber: 10,
  },
  {
    id: 11,
    suraId: 11,
    title: "هود",
    type: "مكية",
    pageNumber: 221,
    souraNumber: 11,
  },
  {
    id: 12,
    suraId: 12,
    title: "يوسف",
    type: "مكية",
    pageNumber: 235,
    souraNumber: 12,
  },
  {
    id: 13,
    suraId: 13,
    title: "الرعد",
    type: "مدنية",
    pageNumber: 249,
    souraNumber: 13,
  },
  {
    id: 14,
    suraId: 14,
    title: "إبراهيم",
    type: "مكية",
    pageNumber: 255,
    souraNumber: 14,
  },
  {
    id: 15,
    suraId: 15,
    title: "الحجر",
    type: "مكية",
    pageNumber: 262,
    souraNumber: 15,
  },
  {
    id: 16,
    suraId: 16,
    title: "النحل",
    type: "مكية",
    pageNumber: 267,
    souraNumber: 16,
  },
  {
    id: 17,
    suraId: 17,
    title: "الإسراء",
    type: "مكية",
    pageNumber: 282,
    souraNumber: 17,
  },
  {
    id: 18,
    suraId: 18,
    title: "الكهف",
    type: "مكية",
    pageNumber: 293,
    souraNumber: 18,
  },
  {
    id: 19,
    suraId: 19,
    title: "مريم",
    type: "مكية",
    pageNumber: 305,
    souraNumber: 19,
  },
  {
    id: 20,
    suraId: 20,
    title: "طه",
    type: "مكية",
    pageNumber: 312,
    souraNumber: 20,
  },
  {
    id: 21,
    suraId: 21,
    title: "الأنبياء",
    type: "مكية",
    pageNumber: 322,
    souraNumber: 21,
  },
  {
    id: 22,
    suraId: 22,
    title: "الحج",
    type: "مدنية",
    pageNumber: 332,
    souraNumber: 22,
  },
  {
    id: 23,
    suraId: 23,
    title: "المؤمنون",
    type: "مكية",
    pageNumber: 342,
    souraNumber: 23,
  },
  {
    id: 24,
    suraId: 24,
    title: "النور",
    type: "مدنية",
    pageNumber: 350,
    souraNumber: 24,
  },
  {
    id: 25,
    suraId: 25,
    title: "الفرقان",
    type: "مكية",
    pageNumber: 359,
    souraNumber: 25,
  },
  {
    id: 26,
    suraId: 26,
    title: "الشعراء",
    type: "مكية",
    pageNumber: 367,
    souraNumber: 26,
  },
  {
    id: 27,
    suraId: 27,
    title: "النمل",
    type: "مكية",
    pageNumber: 377,
    souraNumber: 27,
  },
  {
    id: 28,
    suraId: 28,
    title: "القصص",
    type: "مكية",
    pageNumber: 385,
    souraNumber: 28,
  },
  {
    id: 29,
    suraId: 29,
    title: "العنكبوت",
    type: "مكية",
    pageNumber: 396,
    souraNumber: 29,
  },
  {
    id: 30,
    suraId: 30,
    title: "الروم",
    type: "مكية",
    pageNumber: 404,
    souraNumber: 30,
  },
  {
    id: 31,
    suraId: 31,
    title: "لقمان",
    type: "مكية",
    pageNumber: 411,
    souraNumber: 31,
  },
  {
    id: 32,
    suraId: 32,
    title: "السجدة",
    type: "مكية",
    pageNumber: 415,
    souraNumber: 32,
  },
  {
    id: 33,
    suraId: 33,
    title: "الأحزاب",
    type: "مدنية",
    pageNumber: 418,
    souraNumber: 33,
  },
  {
    id: 34,
    suraId: 34,
    title: "سبأ",
    type: "مكية",
    pageNumber: 428,
    souraNumber: 34,
  },
  {
    id: 35,
    suraId: 35,
    title: "فاطر",
    type: "مكية",
    pageNumber: 434,
    souraNumber: 35,
  },
  {
    id: 36,
    suraId: 36,
    title: "يس",
    type: "مكية",
    pageNumber: 440,
    souraNumber: 36,
  },
  {
    id: 37,
    suraId: 37,
    title: "الصافات",
    type: "مكية",
    pageNumber: 446,
    souraNumber: 37,
  },
  {
    id: 38,
    suraId: 38,
    title: "ص",
    type: "مكية",
    pageNumber: 453,
    souraNumber: 38,
  },
  {
    id: 39,
    suraId: 39,
    title: "الزمر",
    type: "مكية",
    pageNumber: 458,
    souraNumber: 39,
  },
  {
    id: 40,
    suraId: 40,
    title: "غافر",
    type: "مكية",
    pageNumber: 467,
    souraNumber: 40,
  },
  {
    id: 41,
    suraId: 41,
    title: "فصلت",
    type: "مكية",
    pageNumber: 477,
    souraNumber: 41,
  },
  {
    id: 42,
    suraId: 42,
    title: "الشورى",
    type: "مكية",
    pageNumber: 483,
    souraNumber: 42,
  },
  {
    id: 43,
    suraId: 43,
    title: "الزخرف",
    type: "مكية",
    pageNumber: 489,
    souraNumber: 43,
  },
  {
    id: 44,
    suraId: 44,
    title: "الدخان",
    type: "مكية",
    pageNumber: 496,
    souraNumber: 44,
  },
  {
    id: 45,
    suraId: 45,
    title: "الجاثية",
    type: "مكية",
    pageNumber: 499,
    souraNumber: 45,
  },
  {
    id: 46,
    suraId: 46,
    title: "الأحقاف",
    type: "مكية",
    pageNumber: 502,
    souraNumber: 46,
  },
  {
    id: 47,
    suraId: 47,
    title: "محمد",
    type: "مدنية",
    pageNumber: 507,
    souraNumber: 47,
  },
  {
    id: 48,
    suraId: 48,
    title: "الفتح",
    type: "مدنية",
    pageNumber: 511,
    souraNumber: 48,
  },
  {
    id: 49,
    suraId: 49,
    title: "الحجرات",
    type: "مدنية",
    pageNumber: 515,
    souraNumber: 49,
  },
  {
    id: 50,
    suraId: 50,
    title: "ق",
    type: "مكية",
    pageNumber: 518,
    souraNumber: 50,
  },
  {
    id: 51,
    suraId: 51,
    title: "الذاريات",
    type: "مكية",
    pageNumber: 520,
    souraNumber: 51,
  },
  {
    id: 52,
    suraId: 52,
    title: "الطور",
    type: "مكية",
    pageNumber: 523,
    souraNumber: 52,
  },
  {
    id: 53,
    suraId: 53,
    title: "النجم",
    type: "مكية",
    pageNumber: 526,
    souraNumber: 53,
  },
  {
    id: 54,
    suraId: 54,
    title: "القمر",
    type: "مكية",
    pageNumber: 528,
    souraNumber: 54,
  },
  {
    id: 55,
    suraId: 55,
    title: "الرحمن",
    type: "مدنية",
    pageNumber: 531,
    souraNumber: 55,
  },
  {
    id: 56,
    suraId: 56,
    title: "الواقعة",
    type: "مكية",
    pageNumber: 534,
    souraNumber: 56,
  },
  {
    id: 57,
    suraId: 57,
    title: "الحديد",
    type: "مدنية",
    pageNumber: 537,
    souraNumber: 57,
  },
  {
    id: 58,
    suraId: 58,
    title: "المجادلة",
    type: "مدنية",
    pageNumber: 542,
    souraNumber: 58,
  },
  {
    id: 59,
    suraId: 59,
    title: "الحشر",
    type: "مدنية",
    pageNumber: 545,
    souraNumber: 59,
  },
  {
    id: 60,
    suraId: 60,
    title: "الممتحنة",
    type: "مدنية",
    pageNumber: 549,
    souraNumber: 60,
  },
  {
    id: 61,
    suraId: 61,
    title: "الصف",
    type: "مدنية",
    pageNumber: 551,
    souraNumber: 61,
  },
  {
    id: 62,
    suraId: 62,
    title: "الجمعة",
    type: "مدنية",
    pageNumber: 553,
    souraNumber: 62,
  },
  {
    id: 63,
    suraId: 63,
    title: "المنافقون",
    type: "مدنية",
    pageNumber: 554,
    souraNumber: 63,
  },
  {
    id: 64,
    suraId: 64,
    title: "التغابن",
    type: "مدنية",
    pageNumber: 556,
    souraNumber: 64,
  },
  {
    id: 65,
    suraId: 65,
    title: "الطلاق",
    type: "مدنية",
    pageNumber: 558,
    souraNumber: 65,
  },
  {
    id: 66,
    suraId: 66,
    title: "التحريم",
    type: "مدنية",
    pageNumber: 560,
    souraNumber: 66,
  },
  {
    id: 67,
    suraId: 67,
    title: "الملك",
    type: "مكية",
    pageNumber: 562,
    souraNumber: 67,
  },
  {
    id: 68,
    suraId: 68,
    title: "القلم",
    type: "مكية",
    pageNumber: 564,
    souraNumber: 68,
  },
  {
    id: 69,
    suraId: 69,
    title: "الحاقة",
    type: "مكية",
    pageNumber: 566,
    souraNumber: 69,
  },
  {
    id: 70,
    suraId: 70,
    title: "المعارج",
    type: "مكية",
    pageNumber: 568,
    souraNumber: 70,
  },
  {
    id: 71,
    suraId: 71,
    title: "نوح",
    type: "مكية",
    pageNumber: 570,
    souraNumber: 71,
  },
  {
    id: 72,
    suraId: 72,
    title: "الجن",
    type: "مكية",
    pageNumber: 572,
    souraNumber: 72,
  },
  {
    id: 73,
    suraId: 73,
    title: "المزمل",
    type: "مكية",
    pageNumber: 574,
    souraNumber: 73,
  },
  {
    id: 74,
    suraId: 74,
    title: "المدثر",
    type: "مكية",
    pageNumber: 575,
    souraNumber: 74,
  },
  {
    id: 75,
    suraId: 75,
    title: "القيامة",
    type: "مكية",
    pageNumber: 577,
    souraNumber: 75,
  },
  {
    id: 76,
    suraId: 76,
    title: "الإنسان",
    type: "مدنية",
    pageNumber: 578,
    souraNumber: 76,
  },
  {
    id: 77,
    suraId: 77,
    title: "المرسلات",
    type: "مكية",
    pageNumber: 580,
    souraNumber: 77,
  },
  {
    id: 78,
    suraId: 78,
    title: "النبأ",
    type: "مكية",
    pageNumber: 582,
    souraNumber: 78,
  },
  {
    id: 79,
    suraId: 79,
    title: "النازعات",
    type: "مكية",
    pageNumber: 583,
    souraNumber: 79,
  },
  {
    id: 80,
    suraId: 80,
    title: "عبس",
    type: "مكية",
    pageNumber: 585,
    souraNumber: 80,
  },
  {
    id: 81,
    suraId: 81,
    title: "التكوير",
    type: "مكية",
    pageNumber: 586,
    souraNumber: 81,
  },
  {
    id: 82,
    suraId: 82,
    title: "الإنفطار",
    type: "مكية",
    pageNumber: 587,
    souraNumber: 82,
  },
  {
    id: 83,
    suraId: 83,
    title: "المطففين",
    type: "مكية",
    pageNumber: 587,
    souraNumber: 83,
  },
  {
    id: 84,
    suraId: 84,
    title: "الإنشقاق",
    type: "مكية",
    pageNumber: 589,
    souraNumber: 84,
  },
  {
    id: 85,
    suraId: 85,
    title: "البروج",
    type: "مكية",
    pageNumber: 590,
    souraNumber: 85,
  },
  {
    id: 86,
    suraId: 86,
    title: "الطارق",
    type: "مكية",
    pageNumber: 591,
    souraNumber: 86,
  },
  {
    id: 87,
    suraId: 87,
    title: "الأعلى",
    type: "مكية",
    pageNumber: 591,
    souraNumber: 87,
  },
  {
    id: 88,
    suraId: 88,
    title: "الغاشية",
    type: "مكية",
    pageNumber: 592,
    souraNumber: 88,
  },
  {
    id: 89,
    suraId: 89,
    title: "الفجر",
    type: "مكية",
    pageNumber: 593,
    souraNumber: 89,
  },
  {
    id: 90,
    suraId: 90,
    title: "البلد",
    type: "مكية",
    pageNumber: 594,
    souraNumber: 90,
  },
  {
    id: 91,
    suraId: 91,
    title: "الشمس",
    type: "مكية",
    pageNumber: 595,
    souraNumber: 91,
  },
  {
    id: 92,
    suraId: 92,
    title: "الليل",
    type: "مكية",
    pageNumber: 595,
    souraNumber: 92,
  },
  {
    id: 93,
    suraId: 93,
    title: "الضحى",
    type: "مكية",
    pageNumber: 596,
    souraNumber: 93,
  },
  {
    id: 94,
    suraId: 94,
    title: "الشرح",
    type: "مكية",
    pageNumber: 596,
    souraNumber: 94,
  },
  {
    id: 95,
    suraId: 95,
    title: "التين",
    type: "مكية",
    pageNumber: 597,
    souraNumber: 95,
  },
  {
    id: 96,
    suraId: 96,
    title: "العلق",
    type: "مكية",
    pageNumber: 597,
    souraNumber: 96,
  },
  {
    id: 97,
    suraId: 97,
    title: "القدر",
    type: "مكية",
    pageNumber: 598,
    souraNumber: 97,
  },
  {
    id: 98,
    suraId: 98,
    title: "البينة",
    type: "مدنية",
    pageNumber: 598,
    souraNumber: 98,
  },
  {
    id: 99,
    suraId: 99,
    title: "الزلزلة",
    type: "مدنية",
    pageNumber: 599,
    souraNumber: 99,
  },
  {
    id: 100,
    suraId: 100,
    title: "العاديات",
    type: "مكية",
    pageNumber: 599,
    souraNumber: 100,
  },
  {
    id: 101,
    suraId: 101,
    title: "القارعة",
    type: "مكية",
    pageNumber: 600,
    souraNumber: 101,
  },
  {
    id: 102,
    suraId: 102,
    title: "التكاثر",
    type: "مكية",
    pageNumber: 600,
    souraNumber: 102,
  },
  {
    id: 103,
    suraId: 103,
    title: "العصر",
    type: "مكية",
    pageNumber: 601,
    souraNumber: 103,
  },
  {
    id: 104,
    suraId: 104,
    title: "الهمزة",
    type: "مكية",
    pageNumber: 601,
    souraNumber: 104,
  },
  {
    id: 105,
    suraId: 105,
    title: "الفيل",
    type: "مكية",
    pageNumber: 601,
    souraNumber: 105,
  },
  {
    id: 106,
    suraId: 106,
    title: "قريش",
    type: "مكية",
    pageNumber: 602,
    souraNumber: 106,
  },
  {
    id: 107,
    suraId: 107,
    title: "الماعون",
    type: "مكية",
    pageNumber: 602,
    souraNumber: 107,
  },
  {
    id: 108,
    suraId: 108,
    title: "الكوثر",
    type: "مكية",
    pageNumber: 602,
    souraNumber: 108,
  },
  {
    id: 109,
    suraId: 109,
    title: "الكافرون",
    type: "مكية",
    pageNumber: 603,
    souraNumber: 109,
  },
  {
    id: 110,
    suraId: 110,
    title: "النصر",
    type: "مدنية",
    pageNumber: 603,
    souraNumber: 110,
  },
  {
    id: 111,
    suraId: 111,
    title: "المسد",
    type: "مكية",
    pageNumber: 603,
    souraNumber: 111,
  },
  {
    id: 112,
    suraId: 112,
    title: "الإخلاص",
    type: "مكية",
    pageNumber: 604,
    souraNumber: 112,
  },
  {
    id: 113,
    suraId: 113,
    title: "الفلق",
    type: "مكية",
    pageNumber: 604,
    souraNumber: 113,
  },
  {
    id: 114,
    suraId: 114,
    title: "الناس",
    type: "مكية",
    pageNumber: 604,
    souraNumber: 114,
  },
];

const externalParts = Array.from({ length: 30 }, (_, i) => {
  const pageNumber = i === 0 ? 1 : i === 1 ? 22 : 22 + (i - 1) * 20;
  return {
    id: i + 1,
    partId: i + 1,
    title: `الجزء ${i + 1}`,
    pageNumber,
  };
});

const generatePagesObject = (baseURL) =>
  Object.fromEntries(
    Array.from({ length: 604 }, (_, i) => [
      i,
      {
        pageURL: `${baseURL}/${i + 1}.svgz`,
        hotspots: [],
      },
    ])
  );

const initialState = {
  readings: {
    hafs_shuba: {
      id: 1,
      name: "مصحف حفص - بالهامش شعبه",
      key: "hafs_shuba",
      prePagesCount: 3,
      pagesCount: 613,
      index: [
        {
          id: 1,
          suraId: 1,
          title: "الفاتحة",
          type: "مكية",
          pageNumber: 1,
          souraNumber: 1,
        },
        {
          id: 2,
          suraId: 2,
          title: "البقرة",
          type: "مدنية",
          pageNumber: 2,
          souraNumber: 2,
        },
        {
          id: 3,
          suraId: 3,
          title: "آل عمران",
          type: "مدنية",
          pageNumber: 50,
          souraNumber: 3,
        },
        {
          id: 4,
          suraId: 4,
          title: "النساء",
          type: "مدنية",
          pageNumber: 77,
          souraNumber: 4,
        },
        {
          id: 5,
          suraId: 5,
          title: "المائدة",
          type: "مدنية",
          pageNumber: 106,
          souraNumber: 5,
        },
        {
          id: 6,
          suraId: 6,
          title: "الأنعام",
          type: "مكية",
          pageNumber: 128,
          souraNumber: 6,
        },
        {
          id: 7,
          suraId: 7,
          title: "الأعراف",
          type: "مكية",
          pageNumber: 151,
          souraNumber: 7,
        },
        {
          id: 8,
          suraId: 8,
          title: "الأنفال",
          type: "مدنية",
          pageNumber: 177,
          souraNumber: 8,
        },
        {
          id: 9,
          suraId: 9,
          title: "التوبة",
          type: "مدنية",
          pageNumber: 187,
          souraNumber: 9,
        },
        {
          id: 10,
          suraId: 10,
          title: "يونس",
          type: "مكية",
          pageNumber: 208,
          souraNumber: 10,
        },
        {
          id: 11,
          suraId: 11,
          title: "هود",
          type: "مكية",
          pageNumber: 221,
          souraNumber: 11,
        },
        {
          id: 12,
          suraId: 12,
          title: "يوسف",
          type: "مكية",
          pageNumber: 235,
          souraNumber: 12,
        },
        {
          id: 13,
          suraId: 13,
          title: "الرعد",
          type: "مدنية",
          pageNumber: 249,
          souraNumber: 13,
        },
        {
          id: 14,
          suraId: 14,
          title: "إبراهيم",
          type: "مكية",
          pageNumber: 255,
          souraNumber: 14,
        },
        {
          id: 15,
          suraId: 15,
          title: "الحجر",
          type: "مكية",
          pageNumber: 262,
          souraNumber: 15,
        },
        {
          id: 16,
          suraId: 16,
          title: "النحل",
          type: "مكية",
          pageNumber: 267,
          souraNumber: 16,
        },
        {
          id: 17,
          suraId: 17,
          title: "الإسراء",
          type: "مكية",
          pageNumber: 282,
          souraNumber: 17,
        },
        {
          id: 18,
          suraId: 18,
          title: "الكهف",
          type: "مكية",
          pageNumber: 293,
          souraNumber: 18,
        },
        {
          id: 19,
          suraId: 19,
          title: "مريم",
          type: "مكية",
          pageNumber: 305,
          souraNumber: 19,
        },
        {
          id: 20,
          suraId: 20,
          title: "طه",
          type: "مكية",
          pageNumber: 312,
          souraNumber: 20,
        },
        {
          id: 21,
          suraId: 21,
          title: "الأنبياء",
          type: "مكية",
          pageNumber: 322,
          souraNumber: 21,
        },
        {
          id: 22,
          suraId: 22,
          title: "الحج",
          type: "مدنية",
          pageNumber: 332,
          souraNumber: 22,
        },
        {
          id: 23,
          suraId: 23,
          title: "المؤمنون",
          type: "مكية",
          pageNumber: 342,
          souraNumber: 23,
        },
        {
          id: 24,
          suraId: 24,
          title: "النور",
          type: "مدنية",
          pageNumber: 350,
          souraNumber: 24,
        },
        {
          id: 25,
          suraId: 25,
          title: "الفرقان",
          type: "مكية",
          pageNumber: 359,
          souraNumber: 25,
        },
        {
          id: 26,
          suraId: 26,
          title: "الشعراء",
          type: "مكية",
          pageNumber: 367,
          souraNumber: 26,
        },
        {
          id: 27,
          suraId: 27,
          title: "النمل",
          type: "مكية",
          pageNumber: 377,
          souraNumber: 27,
        },
        {
          id: 28,
          suraId: 28,
          title: "القصص",
          type: "مكية",
          pageNumber: 385,
          souraNumber: 28,
        },
        {
          id: 29,
          suraId: 29,
          title: "العنكبوت",
          type: "مكية",
          pageNumber: 396,
          souraNumber: 29,
        },
        {
          id: 30,
          suraId: 30,
          title: "الروم",
          type: "مكية",
          pageNumber: 404,
          souraNumber: 30,
        },
        {
          id: 31,
          suraId: 31,
          title: "لقمان",
          type: "مكية",
          pageNumber: 411,
          souraNumber: 31,
        },
        {
          id: 32,
          suraId: 32,
          title: "السجدة",
          type: "مكية",
          pageNumber: 415,
          souraNumber: 32,
        },
        {
          id: 33,
          suraId: 33,
          title: "الأحزاب",
          type: "مدنية",
          pageNumber: 418,
          souraNumber: 33,
        },
        {
          id: 34,
          suraId: 34,
          title: "سبأ",
          type: "مكية",
          pageNumber: 428,
          souraNumber: 34,
        },
        {
          id: 35,
          suraId: 35,
          title: "فاطر",
          type: "مكية",
          pageNumber: 434,
          souraNumber: 35,
        },
        {
          id: 36,
          suraId: 36,
          title: "يس",
          type: "مكية",
          pageNumber: 440,
          souraNumber: 36,
        },
        {
          id: 37,
          suraId: 37,
          title: "الصافات",
          type: "مكية",
          pageNumber: 446,
          souraNumber: 37,
        },
        {
          id: 38,
          suraId: 38,
          title: "ص",
          type: "مكية",
          pageNumber: 453,
          souraNumber: 38,
        },
        {
          id: 39,
          suraId: 39,
          title: "الزمر",
          type: "مكية",
          pageNumber: 458,
          souraNumber: 39,
        },
        {
          id: 40,
          suraId: 40,
          title: "غافر",
          type: "مكية",
          pageNumber: 467,
          souraNumber: 40,
        },
        {
          id: 41,
          suraId: 41,
          title: "فصلت",
          type: "مكية",
          pageNumber: 477,
          souraNumber: 41,
        },
        {
          id: 42,
          suraId: 42,
          title: "الشورى",
          type: "مكية",
          pageNumber: 483,
          souraNumber: 42,
        },
        {
          id: 43,
          suraId: 43,
          title: "الزخرف",
          type: "مكية",
          pageNumber: 489,
          souraNumber: 43,
        },
        {
          id: 44,
          suraId: 44,
          title: "الدخان",
          type: "مكية",
          pageNumber: 496,
          souraNumber: 44,
        },
        {
          id: 45,
          suraId: 45,
          title: "الجاثية",
          type: "مكية",
          pageNumber: 499,
          souraNumber: 45,
        },
        {
          id: 46,
          suraId: 46,
          title: "الأحقاف",
          type: "مكية",
          pageNumber: 502,
          souraNumber: 46,
        },
        {
          id: 47,
          suraId: 47,
          title: "محمد",
          type: "مدنية",
          pageNumber: 507,
          souraNumber: 47,
        },
        {
          id: 48,
          suraId: 48,
          title: "الفتح",
          type: "مدنية",
          pageNumber: 511,
          souraNumber: 48,
        },
        {
          id: 49,
          suraId: 49,
          title: "الحجرات",
          type: "مدنية",
          pageNumber: 515,
          souraNumber: 49,
        },
        {
          id: 50,
          suraId: 50,
          title: "ق",
          type: "مكية",
          pageNumber: 518,
          souraNumber: 50,
        },
        {
          id: 51,
          suraId: 51,
          title: "الذاريات",
          type: "مكية",
          pageNumber: 520,
          souraNumber: 51,
        },
        {
          id: 52,
          suraId: 52,
          title: "الطور",
          type: "مكية",
          pageNumber: 523,
          souraNumber: 52,
        },
        {
          id: 53,
          suraId: 53,
          title: "النجم",
          type: "مكية",
          pageNumber: 526,
          souraNumber: 53,
        },
        {
          id: 54,
          suraId: 54,
          title: "القمر",
          type: "مكية",
          pageNumber: 528,
          souraNumber: 54,
        },
        {
          id: 55,
          suraId: 55,
          title: "الرحمن",
          type: "مدنية",
          pageNumber: 531,
          souraNumber: 55,
        },
        {
          id: 56,
          suraId: 56,
          title: "الواقعة",
          type: "مكية",
          pageNumber: 534,
          souraNumber: 56,
        },
        {
          id: 57,
          suraId: 57,
          title: "الحديد",
          type: "مدنية",
          pageNumber: 537,
          souraNumber: 57,
        },
        {
          id: 58,
          suraId: 58,
          title: "المجادلة",
          type: "مدنية",
          pageNumber: 542,
          souraNumber: 58,
        },
        {
          id: 59,
          suraId: 59,
          title: "الحشر",
          type: "مدنية",
          pageNumber: 545,
          souraNumber: 59,
        },
        {
          id: 60,
          suraId: 60,
          title: "الممتحنة",
          type: "مدنية",
          pageNumber: 549,
          souraNumber: 60,
        },
        {
          id: 61,
          suraId: 61,
          title: "الصف",
          type: "مدنية",
          pageNumber: 551,
          souraNumber: 61,
        },
        {
          id: 62,
          suraId: 62,
          title: "الجمعة",
          type: "مدنية",
          pageNumber: 553,
          souraNumber: 62,
        },
        {
          id: 63,
          suraId: 63,
          title: "المنافقون",
          type: "مدنية",
          pageNumber: 554,
          souraNumber: 63,
        },
        {
          id: 64,
          suraId: 64,
          title: "التغابن",
          type: "مدنية",
          pageNumber: 556,
          souraNumber: 64,
        },
        {
          id: 65,
          suraId: 65,
          title: "الطلاق",
          type: "مدنية",
          pageNumber: 558,
          souraNumber: 65,
        },
        {
          id: 66,
          suraId: 66,
          title: "التحريم",
          type: "مدنية",
          pageNumber: 560,
          souraNumber: 66,
        },
        {
          id: 67,
          suraId: 67,
          title: "الملك",
          type: "مكية",
          pageNumber: 562,
          souraNumber: 67,
        },
        {
          id: 68,
          suraId: 68,
          title: "القلم",
          type: "مكية",
          pageNumber: 564,
          souraNumber: 68,
        },
        {
          id: 69,
          suraId: 69,
          title: "الحاقة",
          type: "مكية",
          pageNumber: 566,
          souraNumber: 69,
        },
        {
          id: 70,
          suraId: 70,
          title: "المعارج",
          type: "مكية",
          pageNumber: 568,
          souraNumber: 70,
        },
        {
          id: 71,
          suraId: 71,
          title: "نوح",
          type: "مكية",
          pageNumber: 570,
          souraNumber: 71,
        },
        {
          id: 72,
          suraId: 72,
          title: "الجن",
          type: "مكية",
          pageNumber: 572,
          souraNumber: 72,
        },
        {
          id: 73,
          suraId: 73,
          title: "المزمل",
          type: "مكية",
          pageNumber: 574,
          souraNumber: 73,
        },
        {
          id: 74,
          suraId: 74,
          title: "المدثر",
          type: "مكية",
          pageNumber: 575,
          souraNumber: 74,
        },
        {
          id: 75,
          suraId: 75,
          title: "القيامة",
          type: "مكية",
          pageNumber: 577,
          souraNumber: 75,
        },
        {
          id: 76,
          suraId: 76,
          title: "الإنسان",
          type: "مدنية",
          pageNumber: 578,
          souraNumber: 76,
        },
        {
          id: 77,
          suraId: 77,
          title: "المرسلات",
          type: "مكية",
          pageNumber: 580,
          souraNumber: 77,
        },
        {
          id: 78,
          suraId: 78,
          title: "النبأ",
          type: "مكية",
          pageNumber: 582,
          souraNumber: 78,
        },
        {
          id: 79,
          suraId: 79,
          title: "النازعات",
          type: "مكية",
          pageNumber: 583,
          souraNumber: 79,
        },
        {
          id: 80,
          suraId: 80,
          title: "عبس",
          type: "مكية",
          pageNumber: 585,
          souraNumber: 80,
        },
        {
          id: 81,
          suraId: 81,
          title: "التكوير",
          type: "مكية",
          pageNumber: 586,
          souraNumber: 81,
        },
        {
          id: 82,
          suraId: 82,
          title: "الإنفطار",
          type: "مكية",
          pageNumber: 587,
          souraNumber: 82,
        },
        {
          id: 83,
          suraId: 83,
          title: "المطففين",
          type: "مكية",
          pageNumber: 587,
          souraNumber: 83,
        },
        {
          id: 84,
          suraId: 84,
          title: "الإنشقاق",
          type: "مكية",
          pageNumber: 589,
          souraNumber: 84,
        },
        {
          id: 85,
          suraId: 85,
          title: "البروج",
          type: "مكية",
          pageNumber: 590,
          souraNumber: 85,
        },
        {
          id: 86,
          suraId: 86,
          title: "الطارق",
          type: "مكية",
          pageNumber: 591,
          souraNumber: 86,
        },
        {
          id: 87,
          suraId: 87,
          title: "الأعلى",
          type: "مكية",
          pageNumber: 591,
          souraNumber: 87,
        },
        {
          id: 88,
          suraId: 88,
          title: "الغاشية",
          type: "مكية",
          pageNumber: 592,
          souraNumber: 88,
        },
        {
          id: 89,
          suraId: 89,
          title: "الفجر",
          type: "مكية",
          pageNumber: 593,
          souraNumber: 89,
        },
        {
          id: 90,
          suraId: 90,
          title: "البلد",
          type: "مكية",
          pageNumber: 594,
          souraNumber: 90,
        },
        {
          id: 91,
          suraId: 91,
          title: "الشمس",
          type: "مكية",
          pageNumber: 595,
          souraNumber: 91,
        },
        {
          id: 92,
          suraId: 92,
          title: "الليل",
          type: "مكية",
          pageNumber: 595,
          souraNumber: 92,
        },
        {
          id: 93,
          suraId: 93,
          title: "الضحى",
          type: "مكية",
          pageNumber: 596,
          souraNumber: 93,
        },
        {
          id: 94,
          suraId: 94,
          title: "الشرح",
          type: "مكية",
          pageNumber: 596,
          souraNumber: 94,
        },
        {
          id: 95,
          suraId: 95,
          title: "التين",
          type: "مكية",
          pageNumber: 597,
          souraNumber: 95,
        },
        {
          id: 96,
          suraId: 96,
          title: "العلق",
          type: "مكية",
          pageNumber: 597,
          souraNumber: 96,
        },
        {
          id: 97,
          suraId: 97,
          title: "القدر",
          type: "مكية",
          pageNumber: 598,
          souraNumber: 97,
        },
        {
          id: 98,
          suraId: 98,
          title: "البينة",
          type: "مدنية",
          pageNumber: 598,
          souraNumber: 98,
        },
        {
          id: 99,
          suraId: 99,
          title: "الزلزلة",
          type: "مدنية",
          pageNumber: 599,
          souraNumber: 99,
        },
        {
          id: 100,
          suraId: 100,
          title: "العاديات",
          type: "مكية",
          pageNumber: 599,
          souraNumber: 100,
        },
        {
          id: 101,
          suraId: 101,
          title: "القارعة",
          type: "مكية",
          pageNumber: 600,
          souraNumber: 101,
        },
        {
          id: 102,
          suraId: 102,
          title: "التكاثر",
          type: "مكية",
          pageNumber: 600,
          souraNumber: 102,
        },
        {
          id: 103,
          suraId: 103,
          title: "العصر",
          type: "مكية",
          pageNumber: 601,
          souraNumber: 103,
        },
        {
          id: 104,
          suraId: 104,
          title: "الهمزة",
          type: "مكية",
          pageNumber: 601,
          souraNumber: 104,
        },
        {
          id: 105,
          suraId: 105,
          title: "الفيل",
          type: "مكية",
          pageNumber: 601,
          souraNumber: 105,
        },
        {
          id: 106,
          suraId: 106,
          title: "قريش",
          type: "مكية",
          pageNumber: 602,
          souraNumber: 106,
        },
        {
          id: 107,
          suraId: 107,
          title: "الماعون",
          type: "مكية",
          pageNumber: 602,
          souraNumber: 107,
        },
        {
          id: 108,
          suraId: 108,
          title: "الكوثر",
          type: "مكية",
          pageNumber: 602,
          souraNumber: 108,
        },
        {
          id: 109,
          suraId: 109,
          title: "الكافرون",
          type: "مكية",
          pageNumber: 603,
          souraNumber: 109,
        },
        {
          id: 110,
          suraId: 110,
          title: "النصر",
          type: "مدنية",
          pageNumber: 603,
          souraNumber: 110,
        },
        {
          id: 111,
          suraId: 111,
          title: "المسد",
          type: "مكية",
          pageNumber: 603,
          souraNumber: 111,
        },
        {
          id: 112,
          suraId: 112,
          title: "الإخلاص",
          type: "مكية",
          pageNumber: 604,
          souraNumber: 112,
        },
        {
          id: 113,
          suraId: 113,
          title: "الفلق",
          type: "مكية",
          pageNumber: 604,
          souraNumber: 113,
        },
        {
          id: 114,
          suraId: 114,
          title: "الناس",
          type: "مكية",
          pageNumber: 604,
          souraNumber: 114,
        },
      ],
      pages: {
        0: { pageURL: "pages/hafs_shuba/page-001.svg", hotspots: [] },
        1: { pageURL: "pages/hafs_shuba/page-002.svg", hotspots: [] },
        2: { pageURL: "pages/hafs_shuba/page-003.svg", hotspots: [] },
        3: { pageURL: "pages/hafs_shuba/page-004.svg", hotspots: [] },
        4: { pageURL: "pages/hafs_shuba/page-005.svg", hotspots: [] },
        5: { pageURL: "pages/hafs_shuba/page-006.svg", hotspots: [] },
        6: { pageURL: "pages/hafs_shuba/page-007.svg", hotspots: [] },
        7: { pageURL: "pages/hafs_shuba/page-008.svg", hotspots: [] },
        8: { pageURL: "pages/hafs_shuba/page-009.svg", hotspots: [] },
        9: { pageURL: "pages/hafs_shuba/page-010.svg", hotspots: [] },
        10: { pageURL: "pages/hafs_shuba/page-011.svg", hotspots: [] },
        11: { pageURL: "pages/hafs_shuba/page-012.svg", hotspots: [] },
        12: {
          pageURL: "pages/hafs_shuba/page-013.svg",
          hotspots: [
            {
              id: 1,
              wordURL: "pages/shuba/words/page13-sura2-aya67-word14.svg",
              audio: "sounds/shuba/page13-sura2-aya67-word14.mp3",
              x: 295,
              y: 407,
              w: 30,
              h: 30,
              instruction: "إبدال الواو همزة",
              readingTitle: "قراءة شعبه",
              surahTitle: "البقرة",
              ayaNumber: 67,
              pageNumber: 13,
            },
            {
              id: 2,
              wordURL: "pages/shuba/words/page13-sura2-aya67-word14.svg",
              audio: "sounds/shuba/page13-sura2-aya67-word14.mp3",
              x: 0,
              y: 410,
              w: 30,
              h: 90,
              instruction: "إبدال الواو همزة",
              readingTitle: "قراءة شعبه",
              surahTitle: "البقرة",
              ayaNumber: 67,
              pageNumber: 13,
            },
          ],
        },
        13: { pageURL: "pages/hafs_shuba/page-014.svg", hotspots: [] },
        14: { pageURL: "pages/hafs_shuba/page-015.svg", hotspots: [] },
        15: { pageURL: "pages/hafs_shuba/page-016.svg", hotspots: [] },
        16: { pageURL: "pages/hafs_shuba/page-017.svg", hotspots: [] },
      },
      parts: externalParts,
    },
    hafs: {
      id: 2,
      name: "مصحف حفص - رسم عثماني",
      key: "hafs",
      pages: generatePagesObject("https://maknoon.com/quran/hafs"),
      pagesCount: 604,
      index: externalIndex,
      parts: externalParts,
    },
    shuba: {
      id: 3,
      name: "مصحف شعبه - رسم عثماني",
      key: "shuba",
      pages: generatePagesObject("https://maknoon.com/quran/shubah"),
      pagesCount: 604,
      index: externalIndex,
      parts: externalParts,
    },
    warsh: {
      id: 4,
      name: "مصحف ورش - رسم عثماني",
      key: "warsh",
      pages: generatePagesObject("https://maknoon.com/quran/warsh"),
      pagesCount: 604,
      index: externalIndex,
      parts: externalParts,
    },
    qalon: {
      id: 5,
      name: "مصحف قالون - رسم عثماني",
      key: "qalon",
      pages: generatePagesObject("https://maknoon.com/quran/qalon"),
      pagesCount: 604,
      index: externalIndex,
      parts: externalParts,
    },
    douri: {
      id: 6,
      name: "مصحف الدوري - رسم عثماني",
      key: "douri",
      pages: generatePagesObject("https://maknoon.com/quran/douri"),
      pagesCount: 604,
      index: externalIndex,
      parts: externalParts,
    },
  },
  readingsItems: [
    {
      id: 1,
      title: "مصحف حفص - بالهامش شعبه",
      readingKey: "hafs_shuba",
      disabled: false,
      image: "readingItem",
      sideNotes: true,
    },
    {
      id: 2,
      title: "مصحف حفص - رسم عثماني",
      readingKey: "hafs",
      disabled: false,
      image: "readingItem",
      sideNotes: false,
    },
    {
      id: 3,
      title: "مصحف شعبه - رسم عثماني",
      readingKey: "shuba",
      disabled: false,
      image: "readingItem",
      sideNotes: false,
    },
    {
      id: 4,
      title: "مصحف ورش - رسم عثماني",
      readingKey: "warsh",
      disabled: false,
      image: "readingItem",
      sideNotes: false,
    },
    {
      id: 5,
      title: "مصحف قالون - رسم عثماني",
      readingKey: "qalon",
      disabled: false,
      image: "readingItem",
      sideNotes: false,
    },
    {
      id: 6,
      title: "مصحف الدوري - رسم عثماني",
      readingKey: "douri",
      disabled: false,
      image: "readingItem",
      sideNotes: false,
    },
    {
      id: 7,
      title: "مصحف السوسي - رسم عثماني",
      readingKey: "sousi",
      disabled: true,
      image: "readingItem",
      sideNotes: false,
    },
    {
      id: 8,
      title: "مصحف حمزة - رسم عثماني",
      readingKey: "hamza",
      disabled: true,
      image: "readingItem",
      sideNotes: false,
    },
    {
      id: 9,
      title: "مصحف الكسائي - رسم عثماني",
      readingKey: "kisaei",
      disabled: true,
      image: "readingItem",
      sideNotes: false,
    },
    {
      id: 10,
      title: "مصحف خلف - رسم عثماني",
      readingKey: "khalaf",
      disabled: true,
      image: "readingItem",
      sideNotes: false,
    },
  ],
  likedHotspots: [
    {
      id: 1,
      hotspotId: 1,
      userId: 1,
      wordURL: "word-00001-shuba",
      audio: "00001-shuba",
      instruction: "إبدال الواو همزة",
      readingTitle: "قراءة شعبه",
      surahTitle: "البقرة",
      surahId: 2,
      ayaNumber: 67,
      pageNumber: 13,
    },
  ],
};

const envFile =
  process.env.NODE_ENV === "production"
    ? ".env.production"
    : ".env.development";
dotenv.config({ path: envFile });

console.log("DATABASE_CONNECTION_URL:", process.env.DATABASE_CONNECTION_URL);


async function seed() {
  await mongoose.connect(process.env.DATABASE_CONNECTION_URL, {
    useNewUrlParser: true,
    useUnifiedTopology: true,
  });

  // 🔹 Clear collections
  await Promise.all([
    Reading.deleteMany({}),
    ReadingItem.deleteMany({}),
    Sura.deleteMany({}),
    SuraInReading.deleteMany({}),
    Part.deleteMany({}),
    PartInReading.deleteMany({}),
    Page.deleteMany({}),
    Hotspot.deleteMany({}),
  ]);

  // 🔹 Insert Suras (build map by title and suraId)
  const suraMap = {};
  for (const s of externalIndex) {
    const sura = await Sura.create({ title: s.title, type: s.type });
    suraMap[s.title] = sura._id;
    suraMap[s.suraId] = sura._id;
  }

  // 🔹 Insert Parts
  const partMap = {};
  for (const p of externalParts) {
    const part = await Part.create({ title: p.title });
    partMap[p.partId] = part._id;
  }

  const readingKeyToId = {};

  // 🔹 Insert Readings
  for (const [readingKey, readingObj] of Object.entries(
    initialState.readings
  )) {
    const {
      name,
      prePagesCount = 0,
      pagesCount,
      index = [],
      pages = {},
      parts = [],
    } = readingObj;

    const readingDoc = await Reading.create({
      name,
      key: readingKey,
      prePagesCount,
      pagesCount,
    });

    readingKeyToId[readingKey] = readingDoc._id;

    // 🔹 Insert Pages and Hotspots
    for (const [pageNum, pageData] of Object.entries(pages)) {
      const pageDoc = await Page.create({
        readingId: readingDoc._id,
        pageNumber: Number(pageNum),
        pageURL: pageData.pageURL,
        hotspots: [],
      });

      const validHotspots = [];

      for (const h of pageData.hotspots || []) {
        let suraObjectId = null;

        if (h.surahTitle && suraMap[h.surahTitle]) {
          suraObjectId = suraMap[h.surahTitle];
        } else if (h.surahId && suraMap[h.surahId]) {
          suraObjectId = suraMap[h.surahId];
        }

        if (!suraObjectId) {
          console.warn(`⚠️ Skipping hotspot with unknown surah info:`, h);
          continue;
        }

        validHotspots.push({
          ...h,
          pageId: pageDoc._id,
          surahId: suraObjectId,
        });
      }

      const hotspotDocs = await Hotspot.insertMany(validHotspots);
      pageDoc.hotspots = hotspotDocs.map((h) => h._id);
      await pageDoc.save();
    }

    // 🔹 Insert SuraInReading
    await SuraInReading.insertMany(
      index.map((item) => ({
        readingId: readingDoc._id,
        suraId: suraMap[item.suraId],
        pageNumber: item.pageNumber,
        souraNumber: item.souraNumber,
      }))
    );

    // 🔹 Insert PartInReading
    await PartInReading.insertMany(
      parts.map((item) => ({
        readingId: readingDoc._id,
        partId: partMap[item.partId],
        pageNumber: item.pageNumber,
      }))
    );

    console.log(`✅ Inserted reading: ${readingKey}`);
  }

  // 🔹 Insert ReadingItems
  const readingItemDocs = [];

  for (const ri of initialState.readingsItems) {
    let readingId = readingKeyToId[ri.readingKey];
    if (!readingId) {
      const fallback = await Reading.create({
        name: ri.title || "Unnamed",
        key: ri.readingKey,
        pagesCount: 0,
        prePagesCount: 0,
      });
      readingId = fallback._id;
      readingKeyToId[ri.readingKey] = readingId;
      console.warn(`⚠️ Created fallback reading for ${ri.readingKey}`);
    }

    readingItemDocs.push({
      readingId,
      disabled: ri.disabled,
      image: ri.image,
      sideNotes: ri.sideNotes,
    });
  }

  await ReadingItem.insertMany(readingItemDocs);
  console.log("✅ Inserted reading items");

  await mongoose.disconnect();
  console.info("📚 Quraan data seeded successfully!");
}

seed();